server:
  port: 8001
spring:
  application:
    name: user
logging:
  config: classpath:logback-spring.xml
---
#api验签有关配置
application:
  signature:
    enable: true
    app-id: 10086
    secret: a5fbe495127e41da9c2b7f7f6609e39c
    excludes:
      - /v1/open/callback/{platform}
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:3306/easyblog-dev?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
  redis:
    host: ${host}

oauth:
  github:
    client-id: 93aa6fff7267a60ff9b5 #client-id
    client-secret: c1838df46d0730bf243e33741a80425ef54e771e #client-secet
    authorizeUrl: https://github.com/login/oauth/authorize
    redirectUrl: http://127.0.0.1:8001/v1/open/callback/60
  gitee:
    client-id: 668bbc7bf3c356545a8078f95466a65518a52c3384f10876ba81d5bc87749fb1 #client-id
    client-secret: f87ba34b3abf7fe2b7ccca8e0773aafa2ab915e3cacc518bab972a87afa4b2cf #client-secet
    authorizeUrl: https://gitee.com/oauth/authorize
    redirectUrl: http://127.0.0.1:8001/v1/open/callback/70
urls:
  github: https://github.com
  github-api: https://api.github.com
  gitee: https://gitee.com

feign:
  excludes: github.com,gitee.com
---
spring:
  profiles: test

---
spring:
  profiles: stg

---
spring:
  profiles: pro